// Renders every email template to docs/email/previews/*.html with realistic sample data,
// plus an index.html gallery. Pure preview tool — sends nothing.
//
//   npx tsx scripts/email-preview.ts
//   open docs/email/previews/index.html

import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { EMAIL_TEMPLATE_NAMES, TEMPLATE_KIND, renderEmail, type EmailParams } from '../shared/email/index.js';

const OUT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'email', 'previews');

// Sample params shared across templates — only the relevant ones are read per template.
const SAMPLE: EmailParams = {
  firstName: 'Ada',
  confirmUrl: 'https://dreamstreamstudio.ai/api/newsletter/confirm?e=ada@example.com&t=sample',
  actionUrl: 'https://dreamstreamstudio.ai/auth/v1/verify?token=sample&type=signup',
  unsubscribeUrl: 'https://dreamstreamstudio.ai/api/newsletter/unsubscribe?e=ada@example.com&t=sample',
  secureUrl: 'https://dreamstreamstudio.ai/account/security',
  pixelUrl: 'https://dreamstreamstudio.ai/api/email/o/sample.gif',
  token: '123456',
  newEmail: 'ada.new@example.com',
  time: 'Jun 8, 2026, 10:24 AM UTC',
  device: 'Chrome 126 on macOS',
  location: 'Austin, Texas, US',
  ip: '203.0.113.42',
  title: 'New: 8 fresh comic styles ✨',
  body: 'We just dropped woodcut, dieselpunk, ink-wash and 5 more styles.\n\nTry them on your next page — pick a style in the Style panel and regenerate.',
  ctaUrl: 'https://dreamstreamstudio.ai/studio',
  ctaLabel: 'Try the new styles',
  heading: 'Scheduled maintenance this Sunday',
  inviteUrl: 'https://dreamstreamstudio.ai/?invite=DS-7K9F-Q3MX',
  inviterName: 'Akhielesh',
  personalNote: 'You have to try this — built our last comic in an afternoon.',
  code: 'DS-7K9F-Q3MX'
};

mkdirSync(OUT_DIR, { recursive: true });

const rows: string[] = [];
for (const name of EMAIL_TEMPLATE_NAMES) {
  const { subject, html } = renderEmail(name, SAMPLE);
  const file = `${name}.html`;
  writeFileSync(resolve(OUT_DIR, file), html, 'utf8');
  rows.push(
    `<tr><td><a href="./${file}">${name}</a></td><td>${TEMPLATE_KIND[name]}</td><td>${subject.replace(/</g, '&lt;')}</td></tr>`
  );
  console.log(`✓ ${file}  (${TEMPLATE_KIND[name]})  — ${subject}`);
}

const index = `<!doctype html><meta charset="utf-8"><title>DreamStream email previews</title>
<style>body{font-family:system-ui,sans-serif;max-width:760px;margin:40px auto;padding:0 16px}
table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:8px;text-align:left;font-size:14px}
th{background:#FACC15}a{color:#2563EB}</style>
<h1>DreamStream Studio — email previews</h1>
<p>Generated by <code>scripts/email-preview.ts</code>. These are static renders — no email is sent.</p>
<table><thead><tr><th>Template</th><th>Kind</th><th>Subject</th></tr></thead><tbody>
${rows.join('\n')}
</tbody></table>`;
writeFileSync(resolve(OUT_DIR, 'index.html'), index, 'utf8');
console.log(`\nWrote ${EMAIL_TEMPLATE_NAMES.length} previews + index.html to ${OUT_DIR}`);
